name: WorldSDC
version: '${project.version}'
main: com.github.white555gamer.worldsdc.WorldSDC
api-version: 1.19
authors: [ WHERE_WHITE_, WHERE_WHITE_KUN, WHITE555Gamer ]
description: This plugin is for a World Setting view or edit Data Control.
