name: WorldSDC
version: '0.0.1-RELEASE'
main: com.github.white555gamer.worldsdc.WorldSDC
api-version: 1.19
authors: [ WHERE_WHITE_, WHERE_WHITE_KUN, WHITE555Gamer ]
description: This plugin is for a World Setting view or edit Data Control.

commands:
  worldsdc:
    usage: |
      /worldsdc < WorldName > worldborder
      /worldsdc < WorldName > worlddata
      /worldsdc < WorldName > worldlocation
      /worldsdc < WorldName > worldrule
      /worldsdc < WorldName > worldsave
      /worldsdc < WorldName > worldtime
      /worldsdc < WorldName > worldtrait 
      /worldsdc < WorldName > worldweather
      /worldsdc < WorldName > setautosave < true | false >
      /worldsdc < WorldName > setdifficulty < Any Difficulty >
      /worldsdc < WorldName > sethardcore < true | false > 
      /worldsdc < WorldName > setpvp < true | false >
      /worldsdc < WorldName > setkeepspawninmemory < true | false >
      /worldsdc < WorldName > settime < Integer >
      /worldsdc < WorldName > setfulltime < Integer >
      /worldsdc < WorldName > setweatherduration < Integer >
      /worldsdc < WorldName > setclearweatherduration < Integer >
      /worldsdc < WorldName > setthunderduration < Integer >
      /worldsdc < WorldName > setthundering < true | false >
      /worldsdc < WorldName > setstorm < true | false >
    description: |
      For a World Setting view or edit Data Control.
    permission: op
    permission-message: "ERROR: No Operator Permissions."
